minion_uart_capabilities = minion_uart_read(&host, MINION_UART_CAPABILITIES);
minion_uart_host_version = minion_uart_read(&host, MINION_UART_HOST_VERSION);
minion_uart_write(&host, 0x00000001, MINION_UART_SOFTWARE_RESET);
minion_uart_software_reset = minion_uart_read(&host, MINION_UART_SOFTWARE_RESET);
minion_uart_write(&host, 0x0000000F, MINION_UART_POWER_CONTROL);
minion_uart_write(&host, 0x027F003B, MINION_UART_INT_ENABLE);
minion_uart_write(&host, 0x00000000, MINION_UART_SIGNAL_ENABLE);
minion_uart_host_control = minion_uart_read(&host, MINION_UART_HOST_CONTROL);
minion_uart_write(&host, 0x00000000, MINION_UART_HOST_CONTROL);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_clock_control = minion_uart_read(&host, MINION_UART_CLOCK_CONTROL);
minion_uart_write(&host, 0x00000002, MINION_UART_CLOCK_CONTROL);
minion_uart_write(&host, 0x0186A001, MINION_UART_CLOCK_CONTROL);
minion_uart_clock_control = minion_uart_read(&host, MINION_UART_CLOCK_CONTROL);
minion_uart_write(&host, 0x0186A006, MINION_UART_CLOCK_CONTROL);
minion_uart_host_control = minion_uart_read(&host, MINION_UART_HOST_CONTROL);
minion_uart_write(&host, 0x00000000, MINION_UART_HOST_CONTROL);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00000000, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 0);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001AA, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000081A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x40300000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00002903, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00000209, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000031A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00070000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00000909, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00070000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00000D1A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00070000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000071A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00070000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000008, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000333A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 8);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000040, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00FFFFF1, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000063A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 64);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000040, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x80FFFFF1, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000063A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 64);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00070000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000002, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000061A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_host_control = minion_uart_read(&host, MINION_UART_HOST_CONTROL);
minion_uart_write(&host, 0x00000002, MINION_UART_HOST_CONTROL);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00070000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000371A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000040, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x00000D3A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 64);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_clock_control = minion_uart_read(&host, MINION_UART_CLOCK_CONTROL);
minion_uart_write(&host, 0x0186A002, MINION_UART_CLOCK_CONTROL);
minion_uart_write(&host, 0x0C350001, MINION_UART_CLOCK_CONTROL);
minion_uart_clock_control = minion_uart_read(&host, MINION_UART_CLOCK_CONTROL);
minion_uart_write(&host, 0x0C350006, MINION_UART_CLOCK_CONTROL);
minion_uart_host_control = minion_uart_read(&host, MINION_UART_HOST_CONTROL);
minion_uart_write(&host, 0x00000002, MINION_UART_HOST_CONTROL);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000001, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000002, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000003, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000004, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000005, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000006, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000007, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000008, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000009, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x0000000A, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x0000000B, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x0000000C, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x0000000D, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x0000000E, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x0000000F, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x00000200, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000101A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
minion_uart_present_state = minion_uart_read(&host, MINION_UART_PRESENT_STATE);
minion_uart_write(&host, 0x000001F4, MINION_UART_TIMEOUT_CONTROL);
minion_uart_write(&host, 0x00000200, MINION_UART_BLOCK_SIZE);
minion_uart_write(&host, 0x00000001, MINION_UART_BLOCK_COUNT);
minion_uart_write(&host, 0x00000012, MINION_UART_TRANSFER_MODE);
minion_uart_write(&host, 0x00000000, MINION_UART_ARGUMENT);
minion_uart_write(&host, 0x0000113A, MINION_UART_COMMAND);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
cnt = queue_block_read(iobuf, 512);
minion_uart_write(&host, 0x00000001, MINION_UART_INT_STATUS);
minion_uart_int_status = minion_uart_read(&host, MINION_UART_INT_STATUS);
minion_uart_write(&host, 0xFFFFFFFF, MINION_UART_INT_STATUS);
